const GLYPHS: Record<string, string> = {
  "mingcute:pencil": "✎",
  "mingcute:eraser": "⌫",
  "mingcute:bucket": "▰",
  "mingcute:eye": "◉",
  "mingcute:undo-2": "↶",
  "mingcute:redo-2": "↷",
  "mingcute:grid-2": "▦",
  "mingcute:layers": "▤",
  "mingcute:question": "?",
  "mingcute:sparkles-2": "✦",
  "mingcute:file-new": "＋",
  "mingcute:folder-open-2": "↥",
  "mingcute:image-2": "▣",
  "mingcute:save-2": "▰",
  "mingcute:game-2": "◆",
  "mingcute:box-3": "□",
  "mingcute:gallery": "▥",
  "mingcute:back-2": "◀",
  "mingcute:forward-2": "▶",
  "mingcute:pause-fill": "Ⅱ",
  "mingcute:play-fill": "▶",
  "mingcute:add": "＋",
  "mingcute:mouse": "⌁",
  "mingcute:picture": "▣",
  "mingcute:palette": "◈",
  "mingcute:movie": "▤",
  "mingcute:map": "▦",
  "mingcute:bulb": "✦",
  "mingcute:bot": "◎",
  "mingcute:group": "●",
  "mingcute:bulb-2": "✦",
  "mingcute:close-circle": "×",
  "mingcute:alert": "!",
  "mingcute:information": "i",
  "mingcute:lightbulb": "✦",
  "mingcute:cursor": "↖",
  "mingcute:cross": "＋",
};

export function Icon({ icon }: { icon: string }) {
  return <span className="pixel-icon" aria-hidden="true">{GLYPHS[icon] ?? "•"}</span>;
}
